[package]
name = "engine"
version = "0.1.0"
authors = ["Nicolas Gustafsson <nicolas.gustafsson@gmail.com>", "Kevin Zachrisson<kevin.zachrisson@hotmail.com>"]

[dependencies]
winit = "0.13.0"
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"